resources:
- name: concourse-examples
  type: git
  icon: github
  source:
    uri: https://github.com/zak-02/Projects

jobs:
- name: program
  plan:
  - get: concourse-examples
  - task: run
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: busybox
      inputs: # pass concourse-examples into this task step
      - name: concourse-examples
      run:
        path: ./
        args: ["concourse-examples/submodule/netflix.py"]